Make before and after scripts optional based on provided flags
wsharp07/muto pull request #3
Opened 2023-07-20 00:36 UTC by wiked03

_Feel free to discard this... I mostly just wanted to play around wi the cli framework a lil._

Before and After scripts are not super common, so I made them optional based on flags.

Examples I tested:
$ ./bin/dev migrate create add-awesome-column-with-after --after
$ ./bin/dev migrate create add-awesome-column-with-before --before
$ ./bin/dev migrate create add-awesome-column-with-before2 -b
$ ./bin/dev migrate create add-awesome-column-with-before-and-after -b -a
$ ./bin/dev migrate create add-awesome-column-with-before-and-after2 -ab

2023-07-20 01:47 UTC, wsharp07 approved these changes

2023-07-21 04:33 UTC, wsharp07 requested changes
Please add tests 😄

2023-07-23 14:24 UTC, wiked03 commented
> Please add tests 😄

Fixed stuff that you broke and added tests.

Maybe you should be adding some tests too!

![image](https://github.com/wsharp07/muto/assets/10564630/5df48a99-5f28-4cf7-879e-1069294fe9be)

2023-07-23 15:14 UTC, wsharp07 approved these changes

2023-07-23 15:15 UTC, merged